apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: {{NAMESPACE}}  # e.g., qa, uat, prod — replace manually or via GitHub Actions
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # or ClusterIP if using Ingress
